# Generated by Django 4.1.3 on 2023-02-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_on',
        ),
    ]
