# Generated by Django 4.1.3 on 2023-02-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_remove_blogpost_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
