# Generated by Django 4.1.3 on 2023-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_options_blogpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
