# Generated by Django 4.1.3 on 2023-02-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
