# Generated by Django 4.1.3 on 2023-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
