# Generated by Django 4.1.3 on 2023-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_end_of_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
