# Generated by Django 4.1.3 on 2023-02-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
